import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import AppChrome from "@/components/AppChrome";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppChrome>{children}</AppChrome>
        </Providers>
      </body>
    </html>
  );
}
